export type MillionCityDefinition = {
  regionId: string;
  regionName: string;
  regionSlug: string;
  federalDistrict: string;
  cityId: string;
  cityName: string;
  citySlug: string;
  timezone: string;
};

export const RUSSIAN_MILLION_CITIES: MillionCityDefinition[] = [
  {
    regionId: "region_moscow",
    regionName: "Москва",
    regionSlug: "moskva",
    federalDistrict: "Центральный",
    cityId: "city_moscow",
    cityName: "Москва",
    citySlug: "moskva",
    timezone: "Europe/Moscow",
  },
  {
    regionId: "region_spb",
    regionName: "Санкт-Петербург",
    regionSlug: "sankt-peterburg",
    federalDistrict: "Северо-Западный",
    cityId: "city_spb",
    cityName: "Санкт-Петербург",
    citySlug: "sankt-peterburg",
    timezone: "Europe/Moscow",
  },
  {
    regionId: "region_novosibirsk_oblast",
    regionName: "Новосибирская область",
    regionSlug: "novosibirskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_novosibirsk",
    cityName: "Новосибирск",
    citySlug: "novosibirsk",
    timezone: "Asia/Novosibirsk",
  },
  {
    regionId: "region_sverdlovsk_oblast",
    regionName: "Свердловская область",
    regionSlug: "sverdlovskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_yekaterinburg",
    cityName: "Екатеринбург",
    citySlug: "yekaterinburg",
    timezone: "Asia/Yekaterinburg",
  },
  {
    regionId: "region_tatarstan",
    regionName: "Республика Татарстан",
    regionSlug: "respublika-tatarstan",
    federalDistrict: "Приволжский",
    cityId: "city_kazan",
    cityName: "Казань",
    citySlug: "kazan",
    timezone: "Europe/Moscow",
  },
  {
    regionId: "region_nizhny_novgorod_oblast",
    regionName: "Нижегородская область",
    regionSlug: "nizhegorodskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_nizhny_novgorod",
    cityName: "Нижний Новгород",
    citySlug: "nizhny-novgorod",
    timezone: "Europe/Moscow",
  },
  {
    regionId: "region_chelyabinsk_oblast",
    regionName: "Челябинская область",
    regionSlug: "chelyabinskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_chelyabinsk",
    cityName: "Челябинск",
    citySlug: "chelyabinsk",
    timezone: "Asia/Yekaterinburg",
  },
  {
    regionId: "region_krasnoyarsk_krai",
    regionName: "Красноярский край",
    regionSlug: "krasnoyarskiy-kray",
    federalDistrict: "Сибирский",
    cityId: "city_krasnoyarsk",
    cityName: "Красноярск",
    citySlug: "krasnoyarsk",
    timezone: "Asia/Krasnoyarsk",
  },
  {
    regionId: "region_samara_oblast",
    regionName: "Самарская область",
    regionSlug: "samarskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_samara",
    cityName: "Самара",
    citySlug: "samara",
    timezone: "Europe/Samara",
  },
  {
    regionId: "region_bashkortostan",
    regionName: "Республика Башкортостан",
    regionSlug: "respublika-bashkortostan",
    federalDistrict: "Приволжский",
    cityId: "city_ufa",
    cityName: "Уфа",
    citySlug: "ufa",
    timezone: "Asia/Yekaterinburg",
  },
  {
    regionId: "region_rostov_oblast",
    regionName: "Ростовская область",
    regionSlug: "rostovskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_rostov_on_don",
    cityName: "Ростов-на-Дону",
    citySlug: "rostov-na-donu",
    timezone: "Europe/Moscow",
  },
  {
    regionId: "region_krasnodar_krai",
    regionName: "Краснодарский край",
    regionSlug: "krasnodarskiy-kray",
    federalDistrict: "Южный",
    cityId: "city_krasnodar",
    cityName: "Краснодар",
    citySlug: "krasnodar",
    timezone: "Europe/Moscow",
  },
  {
    regionId: "region_omsk_oblast",
    regionName: "Омская область",
    regionSlug: "omskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_omsk",
    cityName: "Омск",
    citySlug: "omsk",
    timezone: "Asia/Omsk",
  },
  {
    regionId: "region_voronezh_oblast",
    regionName: "Воронежская область",
    regionSlug: "voronezhskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_voronezh",
    cityName: "Воронеж",
    citySlug: "voronezh",
    timezone: "Europe/Moscow",
  },
  {
    regionId: "region_perm_krai",
    regionName: "Пермский край",
    regionSlug: "permskiy-kray",
    federalDistrict: "Приволжский",
    cityId: "city_perm",
    cityName: "Пермь",
    citySlug: "perm",
    timezone: "Asia/Yekaterinburg",
  },
  {
    regionId: "region_volgograd_oblast",
    regionName: "Волгоградская область",
    regionSlug: "volgogradskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_volgograd",
    cityName: "Волгоград",
    citySlug: "volgograd",
    timezone: "Europe/Volgograd",
  },
];
