// Справочник российских городов с населением ~100k+ (Росстат, оценки 2020-2023).
// Используется для сидов БД (`prisma/seed.ts`) и как fallback для демо-режима
// (`demo-data.ts`). Slug города уникален в пределах региона; slug региона —
// глобально уникален. Не меняйте slug-и существующих записей: на них завязаны
// upsert-ключи в БД и сохранённые `regionId`/`cityId` у пользователей.
//
// Поле `population` приведено справочно (для документации/отладки) и не
// используется на сервере — нужно лишь чтобы видеть, почему город попал в
// список и иметь возможность отсортировать выдачу при необходимости.
export type RussianCityDefinition = {
  regionId: string;
  regionName: string;
  regionSlug: string;
  federalDistrict: string;
  cityId: string;
  cityName: string;
  citySlug: string;
  timezone: string;
  population?: number;
};

export const RUSSIAN_CITIES: RussianCityDefinition[] = [
  // ===== Центральный федеральный округ =====
  {
    regionId: "region_moscow",
    regionName: "Москва",
    regionSlug: "moskva",
    federalDistrict: "Центральный",
    cityId: "city_moscow",
    cityName: "Москва",
    citySlug: "moskva",
    timezone: "Europe/Moscow",
    population: 13_010_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_balashikha",
    cityName: "Балашиха",
    citySlug: "balashikha",
    timezone: "Europe/Moscow",
    population: 520_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_podolsk",
    cityName: "Подольск",
    citySlug: "podolsk",
    timezone: "Europe/Moscow",
    population: 340_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_khimki",
    cityName: "Химки",
    citySlug: "khimki",
    timezone: "Europe/Moscow",
    population: 265_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_mytishchi",
    cityName: "Мытищи",
    citySlug: "mytishchi",
    timezone: "Europe/Moscow",
    population: 250_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_korolev",
    cityName: "Королёв",
    citySlug: "korolev",
    timezone: "Europe/Moscow",
    population: 225_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_lyubertsy",
    cityName: "Люберцы",
    citySlug: "lyubertsy",
    timezone: "Europe/Moscow",
    population: 210_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_krasnogorsk",
    cityName: "Красногорск",
    citySlug: "krasnogorsk",
    timezone: "Europe/Moscow",
    population: 175_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_elektrostal",
    cityName: "Электросталь",
    citySlug: "elektrostal",
    timezone: "Europe/Moscow",
    population: 158_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_kolomna",
    cityName: "Коломна",
    citySlug: "kolomna",
    timezone: "Europe/Moscow",
    population: 140_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_odintsovo",
    cityName: "Одинцово",
    citySlug: "odintsovo",
    timezone: "Europe/Moscow",
    population: 140_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_domodedovo",
    cityName: "Домодедово",
    citySlug: "domodedovo",
    timezone: "Europe/Moscow",
    population: 140_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_serpukhov",
    cityName: "Серпухов",
    citySlug: "serpukhov",
    timezone: "Europe/Moscow",
    population: 125_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_shchelkovo",
    cityName: "Щёлково",
    citySlug: "shchelkovo",
    timezone: "Europe/Moscow",
    population: 125_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_ramenskoye",
    cityName: "Раменское",
    citySlug: "ramenskoye",
    timezone: "Europe/Moscow",
    population: 120_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_dolgoprudny",
    cityName: "Долгопрудный",
    citySlug: "dolgoprudny",
    timezone: "Europe/Moscow",
    population: 120_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_orekhovo_zuyevo",
    cityName: "Орехово-Зуево",
    citySlug: "orekhovo-zuyevo",
    timezone: "Europe/Moscow",
    population: 115_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_zhukovsky",
    cityName: "Жуковский",
    citySlug: "zhukovsky",
    timezone: "Europe/Moscow",
    population: 110_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_pushkino",
    cityName: "Пушкино",
    citySlug: "pushkino",
    timezone: "Europe/Moscow",
    population: 110_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_reutov",
    cityName: "Реутов",
    citySlug: "reutov",
    timezone: "Europe/Moscow",
    population: 110_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_sergiyev_posad",
    cityName: "Сергиев Посад",
    citySlug: "sergiyev-posad",
    timezone: "Europe/Moscow",
    population: 100_000,
  },
  {
    regionId: "region_moscow_oblast",
    regionName: "Московская область",
    regionSlug: "moskovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_noginsk",
    cityName: "Ногинск",
    citySlug: "noginsk",
    timezone: "Europe/Moscow",
    population: 100_000,
  },
  {
    regionId: "region_belgorod_oblast",
    regionName: "Белгородская область",
    regionSlug: "belgorodskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_belgorod",
    cityName: "Белгород",
    citySlug: "belgorod",
    timezone: "Europe/Moscow",
    population: 390_000,
  },
  {
    regionId: "region_belgorod_oblast",
    regionName: "Белгородская область",
    regionSlug: "belgorodskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_stary_oskol",
    cityName: "Старый Оскол",
    citySlug: "stary-oskol",
    timezone: "Europe/Moscow",
    population: 220_000,
  },
  {
    regionId: "region_bryansk_oblast",
    regionName: "Брянская область",
    regionSlug: "bryanskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_bryansk",
    cityName: "Брянск",
    citySlug: "bryansk",
    timezone: "Europe/Moscow",
    population: 400_000,
  },
  {
    regionId: "region_vladimir_oblast",
    regionName: "Владимирская область",
    regionSlug: "vladimirskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_vladimir",
    cityName: "Владимир",
    citySlug: "vladimir",
    timezone: "Europe/Moscow",
    population: 350_000,
  },
  {
    regionId: "region_vladimir_oblast",
    regionName: "Владимирская область",
    regionSlug: "vladimirskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_kovrov",
    cityName: "Ковров",
    citySlug: "kovrov",
    timezone: "Europe/Moscow",
    population: 140_000,
  },
  {
    regionId: "region_voronezh_oblast",
    regionName: "Воронежская область",
    regionSlug: "voronezhskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_voronezh",
    cityName: "Воронеж",
    citySlug: "voronezh",
    timezone: "Europe/Moscow",
    population: 1_050_000,
  },
  {
    regionId: "region_ivanovo_oblast",
    regionName: "Ивановская область",
    regionSlug: "ivanovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_ivanovo",
    cityName: "Иваново",
    citySlug: "ivanovo",
    timezone: "Europe/Moscow",
    population: 400_000,
  },
  {
    regionId: "region_kaluga_oblast",
    regionName: "Калужская область",
    regionSlug: "kaluzhskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_kaluga",
    cityName: "Калуга",
    citySlug: "kaluga",
    timezone: "Europe/Moscow",
    population: 330_000,
  },
  {
    regionId: "region_kaluga_oblast",
    regionName: "Калужская область",
    regionSlug: "kaluzhskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_obninsk",
    cityName: "Обнинск",
    citySlug: "obninsk",
    timezone: "Europe/Moscow",
    population: 125_000,
  },
  {
    regionId: "region_kostroma_oblast",
    regionName: "Костромская область",
    regionSlug: "kostromskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_kostroma",
    cityName: "Кострома",
    citySlug: "kostroma",
    timezone: "Europe/Moscow",
    population: 270_000,
  },
  {
    regionId: "region_kursk_oblast",
    regionName: "Курская область",
    regionSlug: "kurskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_kursk",
    cityName: "Курск",
    citySlug: "kursk",
    timezone: "Europe/Moscow",
    population: 440_000,
  },
  {
    regionId: "region_kursk_oblast",
    regionName: "Курская область",
    regionSlug: "kurskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_zheleznogorsk_kursk",
    cityName: "Железногорск",
    citySlug: "zheleznogorsk",
    timezone: "Europe/Moscow",
    population: 100_000,
  },
  {
    regionId: "region_lipetsk_oblast",
    regionName: "Липецкая область",
    regionSlug: "lipetskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_lipetsk",
    cityName: "Липецк",
    citySlug: "lipetsk",
    timezone: "Europe/Moscow",
    population: 500_000,
  },
  {
    regionId: "region_orel_oblast",
    regionName: "Орловская область",
    regionSlug: "orlovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_orel",
    cityName: "Орёл",
    citySlug: "orel",
    timezone: "Europe/Moscow",
    population: 300_000,
  },
  {
    regionId: "region_ryazan_oblast",
    regionName: "Рязанская область",
    regionSlug: "ryazanskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_ryazan",
    cityName: "Рязань",
    citySlug: "ryazan",
    timezone: "Europe/Moscow",
    population: 530_000,
  },
  {
    regionId: "region_smolensk_oblast",
    regionName: "Смоленская область",
    regionSlug: "smolenskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_smolensk",
    cityName: "Смоленск",
    citySlug: "smolensk",
    timezone: "Europe/Moscow",
    population: 325_000,
  },
  {
    regionId: "region_tambov_oblast",
    regionName: "Тамбовская область",
    regionSlug: "tambovskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_tambov",
    cityName: "Тамбов",
    citySlug: "tambov",
    timezone: "Europe/Moscow",
    population: 290_000,
  },
  {
    regionId: "region_tver_oblast",
    regionName: "Тверская область",
    regionSlug: "tverskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_tver",
    cityName: "Тверь",
    citySlug: "tver",
    timezone: "Europe/Moscow",
    population: 420_000,
  },
  {
    regionId: "region_tula_oblast",
    regionName: "Тульская область",
    regionSlug: "tulskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_tula",
    cityName: "Тула",
    citySlug: "tula",
    timezone: "Europe/Moscow",
    population: 470_000,
  },
  {
    regionId: "region_tula_oblast",
    regionName: "Тульская область",
    regionSlug: "tulskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_novomoskovsk",
    cityName: "Новомосковск",
    citySlug: "novomoskovsk",
    timezone: "Europe/Moscow",
    population: 115_000,
  },
  {
    regionId: "region_yaroslavl_oblast",
    regionName: "Ярославская область",
    regionSlug: "yaroslavskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_yaroslavl",
    cityName: "Ярославль",
    citySlug: "yaroslavl",
    timezone: "Europe/Moscow",
    population: 575_000,
  },
  {
    regionId: "region_yaroslavl_oblast",
    regionName: "Ярославская область",
    regionSlug: "yaroslavskaya-oblast",
    federalDistrict: "Центральный",
    cityId: "city_rybinsk",
    cityName: "Рыбинск",
    citySlug: "rybinsk",
    timezone: "Europe/Moscow",
    population: 180_000,
  },

  // ===== Северо-Западный федеральный округ =====
  {
    regionId: "region_spb",
    regionName: "Санкт-Петербург",
    regionSlug: "sankt-peterburg",
    federalDistrict: "Северо-Западный",
    cityId: "city_spb",
    cityName: "Санкт-Петербург",
    citySlug: "sankt-peterburg",
    timezone: "Europe/Moscow",
    population: 5_600_000,
  },
  {
    regionId: "region_arkhangelsk_oblast",
    regionName: "Архангельская область",
    regionSlug: "arkhangelskaya-oblast",
    federalDistrict: "Северо-Западный",
    cityId: "city_arkhangelsk",
    cityName: "Архангельск",
    citySlug: "arkhangelsk",
    timezone: "Europe/Moscow",
    population: 340_000,
  },
  {
    regionId: "region_arkhangelsk_oblast",
    regionName: "Архангельская область",
    regionSlug: "arkhangelskaya-oblast",
    federalDistrict: "Северо-Западный",
    cityId: "city_severodvinsk",
    cityName: "Северодвинск",
    citySlug: "severodvinsk",
    timezone: "Europe/Moscow",
    population: 175_000,
  },
  {
    regionId: "region_vologda_oblast",
    regionName: "Вологодская область",
    regionSlug: "vologodskaya-oblast",
    federalDistrict: "Северо-Западный",
    cityId: "city_vologda",
    cityName: "Вологда",
    citySlug: "vologda",
    timezone: "Europe/Moscow",
    population: 315_000,
  },
  {
    regionId: "region_vologda_oblast",
    regionName: "Вологодская область",
    regionSlug: "vologodskaya-oblast",
    federalDistrict: "Северо-Западный",
    cityId: "city_cherepovets",
    cityName: "Череповец",
    citySlug: "cherepovets",
    timezone: "Europe/Moscow",
    population: 310_000,
  },
  {
    regionId: "region_kaliningrad_oblast",
    regionName: "Калининградская область",
    regionSlug: "kaliningradskaya-oblast",
    federalDistrict: "Северо-Западный",
    cityId: "city_kaliningrad",
    cityName: "Калининград",
    citySlug: "kaliningrad",
    timezone: "Europe/Kaliningrad",
    population: 490_000,
  },
  {
    regionId: "region_kareliya",
    regionName: "Республика Карелия",
    regionSlug: "respublika-kareliya",
    federalDistrict: "Северо-Западный",
    cityId: "city_petrozavodsk",
    cityName: "Петрозаводск",
    citySlug: "petrozavodsk",
    timezone: "Europe/Moscow",
    population: 280_000,
  },
  {
    regionId: "region_komi",
    regionName: "Республика Коми",
    regionSlug: "respublika-komi",
    federalDistrict: "Северо-Западный",
    cityId: "city_syktyvkar",
    cityName: "Сыктывкар",
    citySlug: "syktyvkar",
    timezone: "Europe/Moscow",
    population: 245_000,
  },
  {
    regionId: "region_murmansk_oblast",
    regionName: "Мурманская область",
    regionSlug: "murmanskaya-oblast",
    federalDistrict: "Северо-Западный",
    cityId: "city_murmansk",
    cityName: "Мурманск",
    citySlug: "murmansk",
    timezone: "Europe/Moscow",
    population: 280_000,
  },
  {
    regionId: "region_novgorod_oblast",
    regionName: "Новгородская область",
    regionSlug: "novgorodskaya-oblast",
    federalDistrict: "Северо-Западный",
    cityId: "city_velikiy_novgorod",
    cityName: "Великий Новгород",
    citySlug: "velikiy-novgorod",
    timezone: "Europe/Moscow",
    population: 225_000,
  },
  {
    regionId: "region_pskov_oblast",
    regionName: "Псковская область",
    regionSlug: "pskovskaya-oblast",
    federalDistrict: "Северо-Западный",
    cityId: "city_pskov",
    cityName: "Псков",
    citySlug: "pskov",
    timezone: "Europe/Moscow",
    population: 200_000,
  },

  // ===== Южный федеральный округ =====
  {
    regionId: "region_adygeya",
    regionName: "Республика Адыгея",
    regionSlug: "respublika-adygeya",
    federalDistrict: "Южный",
    cityId: "city_maykop",
    cityName: "Майкоп",
    citySlug: "maykop",
    timezone: "Europe/Moscow",
    population: 145_000,
  },
  {
    regionId: "region_kalmykiya",
    regionName: "Республика Калмыкия",
    regionSlug: "respublika-kalmykiya",
    federalDistrict: "Южный",
    cityId: "city_elista",
    cityName: "Элиста",
    citySlug: "elista",
    timezone: "Europe/Moscow",
    population: 105_000,
  },
  {
    regionId: "region_krasnodar_krai",
    regionName: "Краснодарский край",
    regionSlug: "krasnodarskiy-kray",
    federalDistrict: "Южный",
    cityId: "city_krasnodar",
    cityName: "Краснодар",
    citySlug: "krasnodar",
    timezone: "Europe/Moscow",
    population: 1_100_000,
  },
  {
    regionId: "region_krasnodar_krai",
    regionName: "Краснодарский край",
    regionSlug: "krasnodarskiy-kray",
    federalDistrict: "Южный",
    cityId: "city_sochi",
    cityName: "Сочи",
    citySlug: "sochi",
    timezone: "Europe/Moscow",
    population: 470_000,
  },
  {
    regionId: "region_krasnodar_krai",
    regionName: "Краснодарский край",
    regionSlug: "krasnodarskiy-kray",
    federalDistrict: "Южный",
    cityId: "city_novorossiysk",
    cityName: "Новороссийск",
    citySlug: "novorossiysk",
    timezone: "Europe/Moscow",
    population: 330_000,
  },
  {
    regionId: "region_krasnodar_krai",
    regionName: "Краснодарский край",
    regionSlug: "krasnodarskiy-kray",
    federalDistrict: "Южный",
    cityId: "city_armavir",
    cityName: "Армавир",
    citySlug: "armavir",
    timezone: "Europe/Moscow",
    population: 190_000,
  },
  {
    regionId: "region_astrakhan_oblast",
    regionName: "Астраханская область",
    regionSlug: "astrakhanskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_astrakhan",
    cityName: "Астрахань",
    citySlug: "astrakhan",
    timezone: "Europe/Astrakhan",
    population: 475_000,
  },
  {
    regionId: "region_volgograd_oblast",
    regionName: "Волгоградская область",
    regionSlug: "volgogradskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_volgograd",
    cityName: "Волгоград",
    citySlug: "volgograd",
    timezone: "Europe/Volgograd",
    population: 1_000_000,
  },
  {
    regionId: "region_volgograd_oblast",
    regionName: "Волгоградская область",
    regionSlug: "volgogradskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_volzhsky",
    cityName: "Волжский",
    citySlug: "volzhsky",
    timezone: "Europe/Volgograd",
    population: 310_000,
  },
  {
    regionId: "region_volgograd_oblast",
    regionName: "Волгоградская область",
    regionSlug: "volgogradskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_kamyshin",
    cityName: "Камышин",
    citySlug: "kamyshin",
    timezone: "Europe/Volgograd",
    population: 110_000,
  },
  {
    regionId: "region_rostov_oblast",
    regionName: "Ростовская область",
    regionSlug: "rostovskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_rostov_on_don",
    cityName: "Ростов-на-Дону",
    citySlug: "rostov-na-donu",
    timezone: "Europe/Moscow",
    population: 1_140_000,
  },
  {
    regionId: "region_rostov_oblast",
    regionName: "Ростовская область",
    regionSlug: "rostovskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_taganrog",
    cityName: "Таганрог",
    citySlug: "taganrog",
    timezone: "Europe/Moscow",
    population: 250_000,
  },
  {
    regionId: "region_rostov_oblast",
    regionName: "Ростовская область",
    regionSlug: "rostovskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_shakhty",
    cityName: "Шахты",
    citySlug: "shakhty",
    timezone: "Europe/Moscow",
    population: 225_000,
  },
  {
    regionId: "region_rostov_oblast",
    regionName: "Ростовская область",
    regionSlug: "rostovskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_volgodonsk",
    cityName: "Волгодонск",
    citySlug: "volgodonsk",
    timezone: "Europe/Moscow",
    population: 170_000,
  },
  {
    regionId: "region_rostov_oblast",
    regionName: "Ростовская область",
    regionSlug: "rostovskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_novocherkassk",
    cityName: "Новочеркасск",
    citySlug: "novocherkassk",
    timezone: "Europe/Moscow",
    population: 165_000,
  },
  {
    regionId: "region_rostov_oblast",
    regionName: "Ростовская область",
    regionSlug: "rostovskaya-oblast",
    federalDistrict: "Южный",
    cityId: "city_bataysk",
    cityName: "Батайск",
    citySlug: "bataysk",
    timezone: "Europe/Moscow",
    population: 130_000,
  },
  {
    regionId: "region_krym",
    regionName: "Республика Крым",
    regionSlug: "respublika-krym",
    federalDistrict: "Южный",
    cityId: "city_simferopol",
    cityName: "Симферополь",
    citySlug: "simferopol",
    timezone: "Europe/Simferopol",
    population: 340_000,
  },
  {
    regionId: "region_krym",
    regionName: "Республика Крым",
    regionSlug: "respublika-krym",
    federalDistrict: "Южный",
    cityId: "city_kerch",
    cityName: "Керчь",
    citySlug: "kerch",
    timezone: "Europe/Simferopol",
    population: 145_000,
  },
  {
    regionId: "region_sevastopol",
    regionName: "Севастополь",
    regionSlug: "gorod-sevastopol",
    federalDistrict: "Южный",
    cityId: "city_sevastopol",
    cityName: "Севастополь",
    citySlug: "sevastopol",
    timezone: "Europe/Simferopol",
    population: 510_000,
  },

  // ===== Северо-Кавказский федеральный округ =====
  {
    regionId: "region_stavropol_krai",
    regionName: "Ставропольский край",
    regionSlug: "stavropolskiy-kray",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_stavropol",
    cityName: "Ставрополь",
    citySlug: "stavropol",
    timezone: "Europe/Moscow",
    population: 455_000,
  },
  {
    regionId: "region_stavropol_krai",
    regionName: "Ставропольский край",
    regionSlug: "stavropolskiy-kray",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_pyatigorsk",
    cityName: "Пятигорск",
    citySlug: "pyatigorsk",
    timezone: "Europe/Moscow",
    population: 145_000,
  },
  {
    regionId: "region_stavropol_krai",
    regionName: "Ставропольский край",
    regionSlug: "stavropolskiy-kray",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_kislovodsk",
    cityName: "Кисловодск",
    citySlug: "kislovodsk",
    timezone: "Europe/Moscow",
    population: 120_000,
  },
  {
    regionId: "region_stavropol_krai",
    regionName: "Ставропольский край",
    regionSlug: "stavropolskiy-kray",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_nevinnomyssk",
    cityName: "Невинномысск",
    citySlug: "nevinnomyssk",
    timezone: "Europe/Moscow",
    population: 115_000,
  },
  {
    regionId: "region_dagestan",
    regionName: "Республика Дагестан",
    regionSlug: "respublika-dagestan",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_makhachkala",
    cityName: "Махачкала",
    citySlug: "makhachkala",
    timezone: "Europe/Moscow",
    population: 625_000,
  },
  {
    regionId: "region_dagestan",
    regionName: "Республика Дагестан",
    regionSlug: "respublika-dagestan",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_khasavyurt",
    cityName: "Хасавюрт",
    citySlug: "khasavyurt",
    timezone: "Europe/Moscow",
    population: 150_000,
  },
  {
    regionId: "region_dagestan",
    regionName: "Республика Дагестан",
    regionSlug: "respublika-dagestan",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_derbent",
    cityName: "Дербент",
    citySlug: "derbent",
    timezone: "Europe/Moscow",
    population: 125_000,
  },
  {
    regionId: "region_dagestan",
    regionName: "Республика Дагестан",
    regionSlug: "respublika-dagestan",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_kaspiysk",
    cityName: "Каспийск",
    citySlug: "kaspiysk",
    timezone: "Europe/Moscow",
    population: 125_000,
  },
  {
    regionId: "region_chechnya",
    regionName: "Чеченская Республика",
    regionSlug: "chechenskaya-respublika",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_grozny",
    cityName: "Грозный",
    citySlug: "grozny",
    timezone: "Europe/Moscow",
    population: 330_000,
  },
  {
    regionId: "region_severnaya_osetiya",
    regionName: "Республика Северная Осетия — Алания",
    regionSlug: "respublika-severnaya-osetiya-alaniya",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_vladikavkaz",
    cityName: "Владикавказ",
    citySlug: "vladikavkaz",
    timezone: "Europe/Moscow",
    population: 300_000,
  },
  {
    regionId: "region_kabardino_balkariya",
    regionName: "Кабардино-Балкарская Республика",
    regionSlug: "kabardino-balkarskaya-respublika",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_nalchik",
    cityName: "Нальчик",
    citySlug: "nalchik",
    timezone: "Europe/Moscow",
    population: 240_000,
  },
  {
    regionId: "region_ingushetiya",
    regionName: "Республика Ингушетия",
    regionSlug: "respublika-ingushetiya",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_nazran",
    cityName: "Назрань",
    citySlug: "nazran",
    timezone: "Europe/Moscow",
    population: 120_000,
  },
  {
    regionId: "region_karachaevo_cherkessiya",
    regionName: "Карачаево-Черкесская Республика",
    regionSlug: "karachaevo-cherkesskaya-respublika",
    federalDistrict: "Северо-Кавказский",
    cityId: "city_cherkessk",
    cityName: "Черкесск",
    citySlug: "cherkessk",
    timezone: "Europe/Moscow",
    population: 125_000,
  },

  // ===== Приволжский федеральный округ =====
  {
    regionId: "region_tatarstan",
    regionName: "Республика Татарстан",
    regionSlug: "respublika-tatarstan",
    federalDistrict: "Приволжский",
    cityId: "city_kazan",
    cityName: "Казань",
    citySlug: "kazan",
    timezone: "Europe/Moscow",
    population: 1_310_000,
  },
  {
    regionId: "region_tatarstan",
    regionName: "Республика Татарстан",
    regionSlug: "respublika-tatarstan",
    federalDistrict: "Приволжский",
    cityId: "city_naberezhnye_chelny",
    cityName: "Набережные Челны",
    citySlug: "naberezhnye-chelny",
    timezone: "Europe/Moscow",
    population: 530_000,
  },
  {
    regionId: "region_tatarstan",
    regionName: "Республика Татарстан",
    regionSlug: "respublika-tatarstan",
    federalDistrict: "Приволжский",
    cityId: "city_nizhnekamsk",
    cityName: "Нижнекамск",
    citySlug: "nizhnekamsk",
    timezone: "Europe/Moscow",
    population: 240_000,
  },
  {
    regionId: "region_tatarstan",
    regionName: "Республика Татарстан",
    regionSlug: "respublika-tatarstan",
    federalDistrict: "Приволжский",
    cityId: "city_almetyevsk",
    cityName: "Альметьевск",
    citySlug: "almetyevsk",
    timezone: "Europe/Moscow",
    population: 155_000,
  },
  {
    regionId: "region_bashkortostan",
    regionName: "Республика Башкортостан",
    regionSlug: "respublika-bashkortostan",
    federalDistrict: "Приволжский",
    cityId: "city_ufa",
    cityName: "Уфа",
    citySlug: "ufa",
    timezone: "Asia/Yekaterinburg",
    population: 1_130_000,
  },
  {
    regionId: "region_bashkortostan",
    regionName: "Республика Башкортостан",
    regionSlug: "respublika-bashkortostan",
    federalDistrict: "Приволжский",
    cityId: "city_sterlitamak",
    cityName: "Стерлитамак",
    citySlug: "sterlitamak",
    timezone: "Asia/Yekaterinburg",
    population: 270_000,
  },
  {
    regionId: "region_bashkortostan",
    regionName: "Республика Башкортостан",
    regionSlug: "respublika-bashkortostan",
    federalDistrict: "Приволжский",
    cityId: "city_salavat",
    cityName: "Салават",
    citySlug: "salavat",
    timezone: "Asia/Yekaterinburg",
    population: 150_000,
  },
  {
    regionId: "region_bashkortostan",
    regionName: "Республика Башкортостан",
    regionSlug: "respublika-bashkortostan",
    federalDistrict: "Приволжский",
    cityId: "city_neftekamsk",
    cityName: "Нефтекамск",
    citySlug: "neftekamsk",
    timezone: "Asia/Yekaterinburg",
    population: 140_000,
  },
  {
    regionId: "region_bashkortostan",
    regionName: "Республика Башкортостан",
    regionSlug: "respublika-bashkortostan",
    federalDistrict: "Приволжский",
    cityId: "city_oktyabrsky",
    cityName: "Октябрьский",
    citySlug: "oktyabrsky",
    timezone: "Asia/Yekaterinburg",
    population: 115_000,
  },
  {
    regionId: "region_mariy_el",
    regionName: "Республика Марий Эл",
    regionSlug: "respublika-mariy-el",
    federalDistrict: "Приволжский",
    cityId: "city_yoshkar_ola",
    cityName: "Йошкар-Ола",
    citySlug: "yoshkar-ola",
    timezone: "Europe/Moscow",
    population: 280_000,
  },
  {
    regionId: "region_mordoviya",
    regionName: "Республика Мордовия",
    regionSlug: "respublika-mordoviya",
    federalDistrict: "Приволжский",
    cityId: "city_saransk",
    cityName: "Саранск",
    citySlug: "saransk",
    timezone: "Europe/Moscow",
    population: 310_000,
  },
  {
    regionId: "region_udmurtiya",
    regionName: "Удмуртская Республика",
    regionSlug: "udmurtskaya-respublika",
    federalDistrict: "Приволжский",
    cityId: "city_izhevsk",
    cityName: "Ижевск",
    citySlug: "izhevsk",
    timezone: "Europe/Samara",
    population: 640_000,
  },
  {
    regionId: "region_chuvashiya",
    regionName: "Чувашская Республика",
    regionSlug: "chuvashskaya-respublika",
    federalDistrict: "Приволжский",
    cityId: "city_cheboksary",
    cityName: "Чебоксары",
    citySlug: "cheboksary",
    timezone: "Europe/Moscow",
    population: 495_000,
  },
  {
    regionId: "region_chuvashiya",
    regionName: "Чувашская Республика",
    regionSlug: "chuvashskaya-respublika",
    federalDistrict: "Приволжский",
    cityId: "city_novocheboksarsk",
    cityName: "Новочебоксарск",
    citySlug: "novocheboksarsk",
    timezone: "Europe/Moscow",
    population: 125_000,
  },
  {
    regionId: "region_kirov_oblast",
    regionName: "Кировская область",
    regionSlug: "kirovskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_kirov",
    cityName: "Киров",
    citySlug: "kirov",
    timezone: "Europe/Kirov",
    population: 520_000,
  },
  {
    regionId: "region_nizhny_novgorod_oblast",
    regionName: "Нижегородская область",
    regionSlug: "nizhegorodskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_nizhny_novgorod",
    cityName: "Нижний Новгород",
    citySlug: "nizhny-novgorod",
    timezone: "Europe/Moscow",
    population: 1_250_000,
  },
  {
    regionId: "region_nizhny_novgorod_oblast",
    regionName: "Нижегородская область",
    regionSlug: "nizhegorodskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_dzerzhinsk",
    cityName: "Дзержинск",
    citySlug: "dzerzhinsk",
    timezone: "Europe/Moscow",
    population: 225_000,
  },
  {
    regionId: "region_nizhny_novgorod_oblast",
    regionName: "Нижегородская область",
    regionSlug: "nizhegorodskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_arzamas",
    cityName: "Арзамас",
    citySlug: "arzamas",
    timezone: "Europe/Moscow",
    population: 105_000,
  },
  {
    regionId: "region_orenburg_oblast",
    regionName: "Оренбургская область",
    regionSlug: "orenburgskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_orenburg",
    cityName: "Оренбург",
    citySlug: "orenburg",
    timezone: "Asia/Yekaterinburg",
    population: 570_000,
  },
  {
    regionId: "region_orenburg_oblast",
    regionName: "Оренбургская область",
    regionSlug: "orenburgskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_orsk",
    cityName: "Орск",
    citySlug: "orsk",
    timezone: "Asia/Yekaterinburg",
    population: 210_000,
  },
  {
    regionId: "region_penza_oblast",
    regionName: "Пензенская область",
    regionSlug: "penzenskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_penza",
    cityName: "Пенза",
    citySlug: "penza",
    timezone: "Europe/Moscow",
    population: 520_000,
  },
  {
    regionId: "region_perm_krai",
    regionName: "Пермский край",
    regionSlug: "permskiy-kray",
    federalDistrict: "Приволжский",
    cityId: "city_perm",
    cityName: "Пермь",
    citySlug: "perm",
    timezone: "Asia/Yekaterinburg",
    population: 1_050_000,
  },
  {
    regionId: "region_perm_krai",
    regionName: "Пермский край",
    regionSlug: "permskiy-kray",
    federalDistrict: "Приволжский",
    cityId: "city_berezniki",
    cityName: "Березники",
    citySlug: "berezniki",
    timezone: "Asia/Yekaterinburg",
    population: 140_000,
  },
  {
    regionId: "region_samara_oblast",
    regionName: "Самарская область",
    regionSlug: "samarskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_samara",
    cityName: "Самара",
    citySlug: "samara",
    timezone: "Europe/Samara",
    population: 1_170_000,
  },
  {
    regionId: "region_samara_oblast",
    regionName: "Самарская область",
    regionSlug: "samarskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_tolyatti",
    cityName: "Тольятти",
    citySlug: "tolyatti",
    timezone: "Europe/Samara",
    population: 685_000,
  },
  {
    regionId: "region_samara_oblast",
    regionName: "Самарская область",
    regionSlug: "samarskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_syzran",
    cityName: "Сызрань",
    citySlug: "syzran",
    timezone: "Europe/Samara",
    population: 165_000,
  },
  {
    regionId: "region_samara_oblast",
    regionName: "Самарская область",
    regionSlug: "samarskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_novokuybyshevsk",
    cityName: "Новокуйбышевск",
    citySlug: "novokuybyshevsk",
    timezone: "Europe/Samara",
    population: 100_000,
  },
  {
    regionId: "region_saratov_oblast",
    regionName: "Саратовская область",
    regionSlug: "saratovskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_saratov",
    cityName: "Саратов",
    citySlug: "saratov",
    timezone: "Europe/Saratov",
    population: 830_000,
  },
  {
    regionId: "region_saratov_oblast",
    regionName: "Саратовская область",
    regionSlug: "saratovskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_engels",
    cityName: "Энгельс",
    citySlug: "engels",
    timezone: "Europe/Saratov",
    population: 225_000,
  },
  {
    regionId: "region_saratov_oblast",
    regionName: "Саратовская область",
    regionSlug: "saratovskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_balakovo",
    cityName: "Балаково",
    citySlug: "balakovo",
    timezone: "Europe/Saratov",
    population: 185_000,
  },
  {
    regionId: "region_ulyanovsk_oblast",
    regionName: "Ульяновская область",
    regionSlug: "ulyanovskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_ulyanovsk",
    cityName: "Ульяновск",
    citySlug: "ulyanovsk",
    timezone: "Europe/Ulyanovsk",
    population: 620_000,
  },
  {
    regionId: "region_ulyanovsk_oblast",
    regionName: "Ульяновская область",
    regionSlug: "ulyanovskaya-oblast",
    federalDistrict: "Приволжский",
    cityId: "city_dimitrovgrad",
    cityName: "Димитровград",
    citySlug: "dimitrovgrad",
    timezone: "Europe/Ulyanovsk",
    population: 110_000,
  },

  // ===== Уральский федеральный округ =====
  {
    regionId: "region_kurgan_oblast",
    regionName: "Курганская область",
    regionSlug: "kurganskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_kurgan",
    cityName: "Курган",
    citySlug: "kurgan",
    timezone: "Asia/Yekaterinburg",
    population: 310_000,
  },
  {
    regionId: "region_sverdlovsk_oblast",
    regionName: "Свердловская область",
    regionSlug: "sverdlovskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_yekaterinburg",
    cityName: "Екатеринбург",
    citySlug: "yekaterinburg",
    timezone: "Asia/Yekaterinburg",
    population: 1_500_000,
  },
  {
    regionId: "region_sverdlovsk_oblast",
    regionName: "Свердловская область",
    regionSlug: "sverdlovskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_nizhny_tagil",
    cityName: "Нижний Тагил",
    citySlug: "nizhny-tagil",
    timezone: "Asia/Yekaterinburg",
    population: 340_000,
  },
  {
    regionId: "region_sverdlovsk_oblast",
    regionName: "Свердловская область",
    regionSlug: "sverdlovskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_kamensk_uralsky",
    cityName: "Каменск-Уральский",
    citySlug: "kamensk-uralsky",
    timezone: "Asia/Yekaterinburg",
    population: 165_000,
  },
  {
    regionId: "region_sverdlovsk_oblast",
    regionName: "Свердловская область",
    regionSlug: "sverdlovskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_pervouralsk",
    cityName: "Первоуральск",
    citySlug: "pervouralsk",
    timezone: "Asia/Yekaterinburg",
    population: 120_000,
  },
  {
    regionId: "region_tyumen_oblast",
    regionName: "Тюменская область",
    regionSlug: "tyumenskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_tyumen",
    cityName: "Тюмень",
    citySlug: "tyumen",
    timezone: "Asia/Yekaterinburg",
    population: 830_000,
  },
  {
    regionId: "region_tyumen_oblast",
    regionName: "Тюменская область",
    regionSlug: "tyumenskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_tobolsk",
    cityName: "Тобольск",
    citySlug: "tobolsk",
    timezone: "Asia/Yekaterinburg",
    population: 100_000,
  },
  {
    regionId: "region_khmao",
    regionName: "Ханты-Мансийский автономный округ — Югра",
    regionSlug: "khanty-mansiyskiy-avtonomnyy-okrug-yugra",
    federalDistrict: "Уральский",
    cityId: "city_surgut",
    cityName: "Сургут",
    citySlug: "surgut",
    timezone: "Asia/Yekaterinburg",
    population: 395_000,
  },
  {
    regionId: "region_khmao",
    regionName: "Ханты-Мансийский автономный округ — Югра",
    regionSlug: "khanty-mansiyskiy-avtonomnyy-okrug-yugra",
    federalDistrict: "Уральский",
    cityId: "city_nizhnevartovsk",
    cityName: "Нижневартовск",
    citySlug: "nizhnevartovsk",
    timezone: "Asia/Yekaterinburg",
    population: 280_000,
  },
  {
    regionId: "region_khmao",
    regionName: "Ханты-Мансийский автономный округ — Югра",
    regionSlug: "khanty-mansiyskiy-avtonomnyy-okrug-yugra",
    federalDistrict: "Уральский",
    cityId: "city_nefteyugansk",
    cityName: "Нефтеюганск",
    citySlug: "nefteyugansk",
    timezone: "Asia/Yekaterinburg",
    population: 130_000,
  },
  {
    regionId: "region_khmao",
    regionName: "Ханты-Мансийский автономный округ — Югра",
    regionSlug: "khanty-mansiyskiy-avtonomnyy-okrug-yugra",
    federalDistrict: "Уральский",
    cityId: "city_khanty_mansiysk",
    cityName: "Ханты-Мансийск",
    citySlug: "khanty-mansiysk",
    timezone: "Asia/Yekaterinburg",
    population: 105_000,
  },
  {
    regionId: "region_yanao",
    regionName: "Ямало-Ненецкий автономный округ",
    regionSlug: "yamalo-nenetskiy-avtonomnyy-okrug",
    federalDistrict: "Уральский",
    cityId: "city_novy_urengoy",
    cityName: "Новый Уренгой",
    citySlug: "novy-urengoy",
    timezone: "Asia/Yekaterinburg",
    population: 120_000,
  },
  {
    regionId: "region_yanao",
    regionName: "Ямало-Ненецкий автономный округ",
    regionSlug: "yamalo-nenetskiy-avtonomnyy-okrug",
    federalDistrict: "Уральский",
    cityId: "city_noyabrsk",
    cityName: "Ноябрьск",
    citySlug: "noyabrsk",
    timezone: "Asia/Yekaterinburg",
    population: 105_000,
  },
  {
    regionId: "region_chelyabinsk_oblast",
    regionName: "Челябинская область",
    regionSlug: "chelyabinskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_chelyabinsk",
    cityName: "Челябинск",
    citySlug: "chelyabinsk",
    timezone: "Asia/Yekaterinburg",
    population: 1_190_000,
  },
  {
    regionId: "region_chelyabinsk_oblast",
    regionName: "Челябинская область",
    regionSlug: "chelyabinskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_magnitogorsk",
    cityName: "Магнитогорск",
    citySlug: "magnitogorsk",
    timezone: "Asia/Yekaterinburg",
    population: 415_000,
  },
  {
    regionId: "region_chelyabinsk_oblast",
    regionName: "Челябинская область",
    regionSlug: "chelyabinskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_zlatoust",
    cityName: "Златоуст",
    citySlug: "zlatoust",
    timezone: "Asia/Yekaterinburg",
    population: 165_000,
  },
  {
    regionId: "region_chelyabinsk_oblast",
    regionName: "Челябинская область",
    regionSlug: "chelyabinskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_miass",
    cityName: "Миасс",
    citySlug: "miass",
    timezone: "Asia/Yekaterinburg",
    population: 150_000,
  },
  {
    regionId: "region_chelyabinsk_oblast",
    regionName: "Челябинская область",
    regionSlug: "chelyabinskaya-oblast",
    federalDistrict: "Уральский",
    cityId: "city_kopeysk",
    cityName: "Копейск",
    citySlug: "kopeysk",
    timezone: "Asia/Yekaterinburg",
    population: 150_000,
  },

  // ===== Сибирский федеральный округ =====
  {
    regionId: "region_altai_krai",
    regionName: "Алтайский край",
    regionSlug: "altayskiy-kray",
    federalDistrict: "Сибирский",
    cityId: "city_barnaul",
    cityName: "Барнаул",
    citySlug: "barnaul",
    timezone: "Asia/Barnaul",
    population: 625_000,
  },
  {
    regionId: "region_altai_krai",
    regionName: "Алтайский край",
    regionSlug: "altayskiy-kray",
    federalDistrict: "Сибирский",
    cityId: "city_biysk",
    cityName: "Бийск",
    citySlug: "biysk",
    timezone: "Asia/Barnaul",
    population: 200_000,
  },
  {
    regionId: "region_altai_krai",
    regionName: "Алтайский край",
    regionSlug: "altayskiy-kray",
    federalDistrict: "Сибирский",
    cityId: "city_rubtsovsk",
    cityName: "Рубцовск",
    citySlug: "rubtsovsk",
    timezone: "Asia/Barnaul",
    population: 140_000,
  },
  {
    regionId: "region_tyva",
    regionName: "Республика Тыва",
    regionSlug: "respublika-tyva",
    federalDistrict: "Сибирский",
    cityId: "city_kyzyl",
    cityName: "Кызыл",
    citySlug: "kyzyl",
    timezone: "Asia/Krasnoyarsk",
    population: 120_000,
  },
  {
    regionId: "region_khakasiya",
    regionName: "Республика Хакасия",
    regionSlug: "respublika-khakasiya",
    federalDistrict: "Сибирский",
    cityId: "city_abakan",
    cityName: "Абакан",
    citySlug: "abakan",
    timezone: "Asia/Krasnoyarsk",
    population: 185_000,
  },
  {
    regionId: "region_krasnoyarsk_krai",
    regionName: "Красноярский край",
    regionSlug: "krasnoyarskiy-kray",
    federalDistrict: "Сибирский",
    cityId: "city_krasnoyarsk",
    cityName: "Красноярск",
    citySlug: "krasnoyarsk",
    timezone: "Asia/Krasnoyarsk",
    population: 1_190_000,
  },
  {
    regionId: "region_krasnoyarsk_krai",
    regionName: "Красноярский край",
    regionSlug: "krasnoyarskiy-kray",
    federalDistrict: "Сибирский",
    cityId: "city_norilsk",
    cityName: "Норильск",
    citySlug: "norilsk",
    timezone: "Asia/Krasnoyarsk",
    population: 180_000,
  },
  {
    regionId: "region_krasnoyarsk_krai",
    regionName: "Красноярский край",
    regionSlug: "krasnoyarskiy-kray",
    federalDistrict: "Сибирский",
    cityId: "city_achinsk",
    cityName: "Ачинск",
    citySlug: "achinsk",
    timezone: "Asia/Krasnoyarsk",
    population: 100_000,
  },
  {
    regionId: "region_irkutsk_oblast",
    regionName: "Иркутская область",
    regionSlug: "irkutskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_irkutsk",
    cityName: "Иркутск",
    citySlug: "irkutsk",
    timezone: "Asia/Irkutsk",
    population: 620_000,
  },
  {
    regionId: "region_irkutsk_oblast",
    regionName: "Иркутская область",
    regionSlug: "irkutskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_bratsk",
    cityName: "Братск",
    citySlug: "bratsk",
    timezone: "Asia/Irkutsk",
    population: 225_000,
  },
  {
    regionId: "region_irkutsk_oblast",
    regionName: "Иркутская область",
    regionSlug: "irkutskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_angarsk",
    cityName: "Ангарск",
    citySlug: "angarsk",
    timezone: "Asia/Irkutsk",
    population: 225_000,
  },
  {
    regionId: "region_kemerovo_oblast",
    regionName: "Кемеровская область — Кузбасс",
    regionSlug: "kemerovskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_kemerovo",
    cityName: "Кемерово",
    citySlug: "kemerovo",
    timezone: "Asia/Novokuznetsk",
    population: 555_000,
  },
  {
    regionId: "region_kemerovo_oblast",
    regionName: "Кемеровская область — Кузбасс",
    regionSlug: "kemerovskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_novokuznetsk",
    cityName: "Новокузнецк",
    citySlug: "novokuznetsk",
    timezone: "Asia/Novokuznetsk",
    population: 545_000,
  },
  {
    regionId: "region_kemerovo_oblast",
    regionName: "Кемеровская область — Кузбасс",
    regionSlug: "kemerovskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_prokopyevsk",
    cityName: "Прокопьевск",
    citySlug: "prokopyevsk",
    timezone: "Asia/Novokuznetsk",
    population: 190_000,
  },
  {
    regionId: "region_novosibirsk_oblast",
    regionName: "Новосибирская область",
    regionSlug: "novosibirskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_novosibirsk",
    cityName: "Новосибирск",
    citySlug: "novosibirsk",
    timezone: "Asia/Novosibirsk",
    population: 1_620_000,
  },
  {
    regionId: "region_novosibirsk_oblast",
    regionName: "Новосибирская область",
    regionSlug: "novosibirskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_berdsk",
    cityName: "Бердск",
    citySlug: "berdsk",
    timezone: "Asia/Novosibirsk",
    population: 105_000,
  },
  {
    regionId: "region_omsk_oblast",
    regionName: "Омская область",
    regionSlug: "omskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_omsk",
    cityName: "Омск",
    citySlug: "omsk",
    timezone: "Asia/Omsk",
    population: 1_115_000,
  },
  {
    regionId: "region_tomsk_oblast",
    regionName: "Томская область",
    regionSlug: "tomskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_tomsk",
    cityName: "Томск",
    citySlug: "tomsk",
    timezone: "Asia/Tomsk",
    population: 570_000,
  },
  {
    regionId: "region_tomsk_oblast",
    regionName: "Томская область",
    regionSlug: "tomskaya-oblast",
    federalDistrict: "Сибирский",
    cityId: "city_seversk",
    cityName: "Северск",
    citySlug: "seversk",
    timezone: "Asia/Tomsk",
    population: 105_000,
  },

  // ===== Дальневосточный федеральный округ =====
  {
    regionId: "region_buryatiya",
    regionName: "Республика Бурятия",
    regionSlug: "respublika-buryatiya",
    federalDistrict: "Дальневосточный",
    cityId: "city_ulan_ude",
    cityName: "Улан-Удэ",
    citySlug: "ulan-ude",
    timezone: "Asia/Irkutsk",
    population: 440_000,
  },
  {
    regionId: "region_yakutiya",
    regionName: "Республика Саха (Якутия)",
    regionSlug: "respublika-saha-yakutiya",
    federalDistrict: "Дальневосточный",
    cityId: "city_yakutsk",
    cityName: "Якутск",
    citySlug: "yakutsk",
    timezone: "Asia/Yakutsk",
    population: 330_000,
  },
  {
    regionId: "region_zabaykalsky_krai",
    regionName: "Забайкальский край",
    regionSlug: "zabaykalskiy-kray",
    federalDistrict: "Дальневосточный",
    cityId: "city_chita",
    cityName: "Чита",
    citySlug: "chita",
    timezone: "Asia/Chita",
    population: 350_000,
  },
  {
    regionId: "region_kamchatsky_krai",
    regionName: "Камчатский край",
    regionSlug: "kamchatskiy-kray",
    federalDistrict: "Дальневосточный",
    cityId: "city_petropavlovsk_kamchatsky",
    cityName: "Петропавловск-Камчатский",
    citySlug: "petropavlovsk-kamchatsky",
    timezone: "Asia/Kamchatka",
    population: 165_000,
  },
  {
    regionId: "region_primorsky_krai",
    regionName: "Приморский край",
    regionSlug: "primorskiy-kray",
    federalDistrict: "Дальневосточный",
    cityId: "city_vladivostok",
    cityName: "Владивосток",
    citySlug: "vladivostok",
    timezone: "Asia/Vladivostok",
    population: 600_000,
  },
  {
    regionId: "region_primorsky_krai",
    regionName: "Приморский край",
    regionSlug: "primorskiy-kray",
    federalDistrict: "Дальневосточный",
    cityId: "city_ussuriysk",
    cityName: "Уссурийск",
    citySlug: "ussuriysk",
    timezone: "Asia/Vladivostok",
    population: 180_000,
  },
  {
    regionId: "region_primorsky_krai",
    regionName: "Приморский край",
    regionSlug: "primorskiy-kray",
    federalDistrict: "Дальневосточный",
    cityId: "city_nakhodka",
    cityName: "Находка",
    citySlug: "nakhodka",
    timezone: "Asia/Vladivostok",
    population: 150_000,
  },
  {
    regionId: "region_primorsky_krai",
    regionName: "Приморский край",
    regionSlug: "primorskiy-kray",
    federalDistrict: "Дальневосточный",
    cityId: "city_artyom",
    cityName: "Артём",
    citySlug: "artyom",
    timezone: "Asia/Vladivostok",
    population: 115_000,
  },
  {
    regionId: "region_khabarovsk_krai",
    regionName: "Хабаровский край",
    regionSlug: "khabarovskiy-kray",
    federalDistrict: "Дальневосточный",
    cityId: "city_khabarovsk",
    cityName: "Хабаровск",
    citySlug: "khabarovsk",
    timezone: "Asia/Vladivostok",
    population: 620_000,
  },
  {
    regionId: "region_khabarovsk_krai",
    regionName: "Хабаровский край",
    regionSlug: "khabarovskiy-kray",
    federalDistrict: "Дальневосточный",
    cityId: "city_komsomolsk_on_amur",
    cityName: "Комсомольск-на-Амуре",
    citySlug: "komsomolsk-na-amure",
    timezone: "Asia/Vladivostok",
    population: 240_000,
  },
  {
    regionId: "region_amur_oblast",
    regionName: "Амурская область",
    regionSlug: "amurskaya-oblast",
    federalDistrict: "Дальневосточный",
    cityId: "city_blagoveshchensk",
    cityName: "Благовещенск",
    citySlug: "blagoveshchensk",
    timezone: "Asia/Yakutsk",
    population: 225_000,
  },
  {
    regionId: "region_sakhalin_oblast",
    regionName: "Сахалинская область",
    regionSlug: "sakhalinskaya-oblast",
    federalDistrict: "Дальневосточный",
    cityId: "city_yuzhno_sakhalinsk",
    cityName: "Южно-Сахалинск",
    citySlug: "yuzhno-sakhalinsk",
    timezone: "Asia/Sakhalin",
    population: 200_000,
  },
];

// Обратная совместимость: старое имя `RUSSIAN_MILLION_CITIES` все ещё может
// использоваться внешним кодом. Экспорт-алиас. Также сохраняем тип-алиас
// `MillionCityDefinition` для совместимости.
export const RUSSIAN_MILLION_CITIES = RUSSIAN_CITIES;
export type MillionCityDefinition = RussianCityDefinition;
